name: ex01
on: 
  workflow_dispatch:
  schedule:
      - cron: "*/5 * * * *"
jobs:
  author_info:
    runs-on: ubuntu-latest
steps:
- name: Check out this repo
  uses: actions/checkout@v4
   - name: Fetch API Data 
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://example.com
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.AUTHOR_NAME }}"} }'
env:
  GLOBAL_VAR: ${{ secrets.AUTHOR_NAME }}
